# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 392c6eafcee9fa82f680e9d3d3ad13b73459be90b89c90283ba25e4b7d62fc98d062f1c5701c23e981fc551a6949e041f7d8f300e4b64373bd28afc9513a3273

test:
  secret_key_base: 0851540f2acbaea31d580cce154e3d95832914b480a42cb737aab1465e640a0726c29c8b6e9be0f2ddf4075696de02f905644e1a0746f9f8704af72a61214a4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
